name: Trigger auto deployment for cassavaflaskapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/cassavaflaskapp-AutoDeployTrigger-9574f24f-649d-4ba8-a0ee-d664abed40ee.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cassavaflaskacr.azurecr.io
          username: ${{ secrets.CASSAVAFLASKAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.CASSAVAFLASKAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cassavaflaskacr.azurecr.io/cassavaflaskapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CASSAVAFLASKAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n cassavaflaskapp -g cassavaflaskgroup --server cassavaflaskacr.azurecr.io --username  ${{ secrets.CASSAVAFLASKAPP_REGISTRY_USERNAME }} --password ${{ secrets.CASSAVAFLASKAPP_REGISTRY_PASSWORD }}
            az containerapp update -n cassavaflaskapp -g cassavaflaskgroup --image cassavaflaskacr.azurecr.io/cassavaflaskapp:${{ github.sha }}
